print('A la víbora, víbora')
print('\t De la mar, de la mar')
print('\t\t Por aquí pueden pasar')
print('\t Los de adelante corren mucho')
print('\t\t Y los de atrás se quedarán')
print('A la víbora, víbora')
print('\t De la mar, de la mar')
print('\t\t Por aquí pueden pasar')
print('\t Los de adelante corren mucho')
print('\t\t Y los de atrás se quedarán')
print('\t\t Tras, tras, tras')
